---
label: Site Config
hide_body: true
fields:
- type: text
  name: baseURL
  label: baseURL
  default: "/"
  hidden: true
- type: text
  name: languageCode
  label: Language Code
  default: en
- type: text
  name: title
  label: Title
  default: The site title
- type: text
  name: theme
  label: theme
  hidden: true
pages:
- config.toml
